services:
    web:
        build:
            context: .
            dockerfile: ./docker/Dockerfile.dev
        ports:
            - "4000:4000"
        volumes:
            - ./locations:/usr/src/app
        env_file:
            - ./.env
        command: ["air"]
        depends_on:
            - db
    migrate:
        image: migrate/migrate
        volumes:
            - ./locations/migrations:/migrations
        command: [
            "-path",
            "/migrations",
            "-database",
            "postgres://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}?sslmode=disable",
            "up"
        ]
        links:
            - db
    db:
        image: postgres:alpine
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
            - POSTGRES_DB=${DB_NAME}
        ports:
            - "${DB_PORT}:5432"
        volumes:
            - pg-volume:/var/lib/postgresql/data

volumes:
    pg-volume:
