services:
    web_prod:
        build:
            context: .
            dockerfile: ./docker/Dockerfile.prod
        ports:
            - "4000:4000"
        command: ["./bin"]
        depends_on:
            - db_prod
        environment:
            - DB_USER=${DB_USER}
            - DB_PASS=${DB_PASS}
            - DB_NAME=${DB_NAME}
            - DB_HOST=${DB_HOST_PROD}
            - DB_PORT=${DB_PORT}
            - MAX_OPEN_CONNS=${MAX_OPEN_CONNS}
            - MAX_IDLE_CONNS=${MAX_IDLE_CONNS}
            - MAX_IDLE_TIME=${MAX_IDLE_TIME}
            - SERVER_PORT=${SERVER_PORT}
            - ENV=production
    migrate:
        image: migrate/migrate
        volumes:
            - ./locations/migrations:/migrations
        command: [
            "-path",
            "/migrations",
            "-database",
            "postgres://${DB_USER}:${DB_PASS}@${DB_HOST_PROD}:5432/${DB_NAME}?sslmode=disable",
            "up"
        ]
        links:
            - db_prod
    db_prod:
        image: postgres:alpine
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
            - POSTGRES_DB=${DB_NAME}
        volumes:
            - pg-prod-volume:/var/lib/postgresql/data

volumes:
    pg-prod-volume:
