services:
    web_prod:
        build:
            context: .
            dockerfile: ./docker/Dockerfile.prod
        ports:
            - "4000:4000"
        volumes:
            - ./locations:/usr/src/app
        env_file:
            - ./.env
        command: ["./locations"]
        depends_on:
            - db_prod
    migrate:
        image: migrate/migrate
        volumes:
            - ./locations/migrations:/migrations
        command: [
            "-path",
            "/migrations",
            "-database",
            "postgres://${DB_USER}:${DB_PASS}@${DB_HOST}:5432/${DB_NAME}?sslmode=disable",
            "up"
        ]
        links:
            - db_prod
    db_prod:
        image: postgres:alpine
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
            - POSTGRES_DB=${DB_NAME}
        volumes:
            - pg-prod-volume:/var/lib/postgresql/data

volumes:
    pg-prod-volume:
