FROM golang:1.21 AS builder

WORKDIR /usr/src/app

COPY go.mod go.sum .
RUN go mod download
RUN go mod tidy

COPY cmd/ cmd/
COPY internal/ internal/

RUN CGO_ENABLED=0 GOOS=linux go build -o ./location ./cmd/api

FROM gcr.io/distroless/static-debian12 AS release

WORKDIR /
COPY --from=builder /usr/src/app/location .
COPY swagger.yaml .

EXPOSE 4000
