FROM golang:1.21

WORKDIR /usr/src/app

RUN go install github.com/cosmtrek/air@latest

COPY go.mod go.sum .
RUN go mod download
RUN go mod tidy

COPY cmd/ cmd/
COPY internal/ internal/
COPY swagger.yaml .
